---
services:
  openpcdet:
    image: openpcdet-image:V1
    container_name: openpcdet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SDL_VIDEODRIVER=x11
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/smueck/data:/storage
      - /home/smueck/OpenPCDet:/app/OpenPCDet
    ports:
      - "2222:22"
      - "6006:6006"
#    command: /usr/sbin/sshd
    ipc: host
    runtime: nvidia
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
